<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-16RSFON" failures="1" tests="1" name="cucumber.TestNGTestRunner" time="22.540" errors="0" timestamp="2025-04-16T14:04:29 IST" skipped="0">
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="22.540">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at rohanacademy.stepDefinitions.StepDefinitionImpl.message_displayed_confirmationPage(StepDefinitionImpl.java:54)
at âœ½."THANK YOU FOR THE ORDER." message is displayed on ConfirmationPage(file:///C:/selenium_learning/SeleniumFrameworkDesign/src/test/java/cucumber/SubmitOrder.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumber.TestNGTestRunner -->
